name: ssi-service-ci

# when:
#   - a pull request is opened against main
#   - commits are pushed to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # used to run action manually via the UI
  workflow_dispatch:

jobs:
  vulnerability-scan: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2
          cache: true

      - name: Install Mage
        run: go install github.com/magefile/mage

      - name: Check Vulnerabilities
        run: mage -v vuln

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.2
        cache: true

    - name: Install mage
      run: go install github.com/magefile/mage

    - name: Build library
      run: mage build

    - name: Test
      run: mage CITest

    - name: Generate Swagger
      run: mage spec

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Build binary
      if: ${{ github.ref == 'refs/heads/main' }}
      run: mage artifact

    - uses: actions/upload-artifact@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        path: bin/ssi-service
